### ISSUE TITLE
series "creator" seems to be broken

### ISSUE THREAD

**Issue by meeotch** [cinemagoer/cinemagoer#275]
#### Issue description

parsing of series "creator" seems to be broken

#### Version of IMDbPY, Python and OS

- **Python:** 3.6.9
- **IMDbPY:** 6.8
- **OS:** ('Linux', '5.3.0-62-generic', '#56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020', 'x86_64', 'x86_64')

#### Steps to reproduce the issue

```
ia = IMDb()
m = ia.get_movie("2861424")
print(m['creator'])
```

#### What's the expected result?
```
[<Person id:1363595[http] name:_Dan Harmon_>, <Person id:1551598[http] name:_Justin Roiland_>]
```

#### What's the actual result?
```
KeyError: 'creator'
```

#### Additional details
The current code for extracting series creators is:
```
                foreach='//td[starts-with(text(), "Creator")]/..//a',
```
Changing it to match the code for extracting writers/directors seems to work:
```
                foreach='//div[starts-with(normalize-space(text()), "Creator")]/ul/li[1]/a',
```
Although why this is wasn't entirely clear to me.  The actual structure of the html is this:
```
    <div class="credit_summary_item">
        <h4 class="inline">Creators:</h4>
        <a href="/name/nm1363595/?ref_=tt_ov_wr">Dan Harmon</a>, 
        <a href="/name/nm1551598/?ref_=tt_ov_wr">Justin Roiland</a>    
    </div>
```

Which looks a lot more like `..//a` than `ul/li[1]/a` to my untrained eye.  But the latter form seems to work.  (Note that Directors and Writers seem to have the same html form given above.)

**Comment by meeotch** [comment]
Minor update:  I cleared up my confusion about the `ul/li` business.  I didn't realize that imdbpy was pulling info from the `/reference` page, instead of the regular-for-humans page.  So the fix I mentioned above now makes sense to me, in addition to actually working.

One interesting item:  It seems like for a few shows, the regular-for-humans page shows a Creator, but the reference page shows only a Director:

https://www.imdb.com/title/tt0465316/?ref_=nv_sr_srsg_0
https://www.imdb.com/title/tt0465316/reference

Weird.  Some other examples:

https://www.imdb.com/title/tt4230076/?ref_=nv_sr_srsg_0
https://www.imdb.com/title/tt5580146/?ref_=nv_sr_srsg_0
https://www.imdb.com/title/tt7049682/?ref_=nv_sr_srsg_0

**Comment by alberanid** [comment]
@meeotch correct me if I'm wrong: can we conclude that the "Creator" field is no longer present in the "reference" page?

**Comment by meeotch** [comment]
@alberanid - no, Creator is still on the reference page.  It's just that the reference page and the "regular" page doesn't match for some shows.  (Examples above.)  That, and the fact that the code for parsing Creators wasn't working.

**Comment by alberanid** [comment]
Is it okay to close this issue?  Does the commit https://github.com/alberanid/imdbpy/commit/4381b75dbe256cda4aba0fbd74ac1ba608114571 fix it?

If there are other improvements, please open a pull request.  Thanks!

**Comment by meeotch** [comment]
Hi - thanks for the fix.  I'm in the process of deploying the project that I originally implemented the Creator fix for, so probably won't be able to update my imdbpy until that's finally put to bed.  But I'd say if the fix works with the examples I gave, and any others you may have found, then you can close this issue.

fyi - For that same project, I implemented a similar change for "Star", and added a rule for the "Also Known For" section.  As mentioned, I'm a bit under the gun with this project (and I'm not sure everyone would want those changes anyway) - so not sure about a pull request.  But if you'd like to look at the code, I'm happy to provide it.  (It's just one new Known For rule - the Star fix is identical to the Creator one.)

Although now that I'm talking about it - I guess I could just create a subclass for my project-specific additions, and override the parent class rules.  But you know - moving quickly, took the path of least resistance.

**Comment by alberanid** [comment]
@meeotch don't worry, a PR is welcome whenever you have time. :+1:

**Comment by BrandonKMLee** [comment]
Also see https://github.com/alberanid/imdbpy/issues/328

**Comment by meeotch** [comment]
I know that there are now several open issues on related topics, but one more data point:  As of today, or the past couple days, it's gotten worse.  My test script above now fails consistently many times in a row.

I've also noticed that tinyMediaManger comes up with no results when scraping with the imdb scraper.  A week ago, I'd be able to re-submit, and get results.  But now I have to leave it idle for 5-10min in order to get results.

So it does feel like some sort of spam protection / throttling on the part of imdb.com.

**Comment by BrandonKMLee** [comment]
It might be that, have someone checked if it is more a bot detection (UserAgent) or UX change issue?

**Comment by meeotch** [comment]
Shoot - I'm sorry...  I posted that last comment to the wrong issue.  I'll repost to #418.
