### ISSUE TITLE
Get_top50_movies_by_genre includes TV Shows

### ISSUE THREAD

**Issue by rg9400** [cinemagoer/cinemagoer#373]
#### Issue description

Latest commit to add support for `get_top50_movies_by_genre` at https://github.com/alberanid/imdbpy/commit/b8650d944d00ee459a495fa4f12f18ae701a2ba8

This seems to include TV shows in the list as well. Ideally, the method reflects that it will grab both, or it filters out TV vs movies.

#### Version of IMDbPY, Python and OS
IMDbPY: IMDbPY-2022.1.16
Python: 3.10.1
OS: Windows 10

#### Steps to reproduce the issue

```python
#!/usr/bin/env python

from imdb import IMDb
ia = IMDb()
test = ia.get_top50_movies_by_genres("action")
test[0]
```

#### What's the expected result?

- A movie item

#### What's the actual result?

- <Movie id:7221388[http] title:_"Cobra Kai" (2018)_> which is a TV show

**Comment by alberanid** [comment]
Fixed by PR #374
