### ISSUE TITLE
Migrate to a new name: cinemagoer 

### ISSUE THREAD

**Issue by alberanid** [cinemagoer/cinemagoer#378]
We are moving the repository to a new home: cinemagoer/cinemagoer

**Comment by MaximShidlovski23** [comment]
> We are moving the repository to a new home: cinemagoer/cinemagoer

Hi, what is the reason for renaming?

**Comment by alberanid** [comment]
well, moving it to its own organization was long overdue. We will try to avoid too much disruption for developers.
