### ISSUE TITLE
How do I get the role an actor plays.

### ISSUE THREAD

**Issue by insundaycathy** [cinemagoer/cinemagoer#384]
#### Issue description

when I use movie['cast'] I can only get the actor id and name, how can I get the name of the role this actor plays in the movie?

-

**Comment by alberanid** [comment]
hi, you can access the `.currentRole` property of a Person instance.

The documentation is here: https://cinemagoer.readthedocs.io/en/latest/usage/role.html?highlight=currentRole#roles
