### ISSUE TITLE
Doesn't expose analyze_title function from utils

### ISSUE THREAD

**Issue by more-pepsi** [cinemagoer/cinemagoer#386]
#### Issue description
Title says it all. Its documented that you can use this function, but I can't import it anywhere

```python
#!/usr/bin/env python

# your code here
```

#### What's the expected result?

- 

#### What's the actual result?

- 

#### Additional details

-

**Comment by alberanid** [comment]
An example:
```python

from imdb.utils import analyze_title
analyze_title('The Matrix (1999)')
```

Will output:
```
{'title': 'The Matrix', 'year': 1999, 'kind': 'movie'}
```
