### ISSUE TITLE
'Hangar 10' breaks movie search

### ISSUE THREAD

**Issue by 81ed** [cinemagoer/cinemagoer#395]
#### Issue description

search_movie returns a "IMDbParserError: invalid title:" when searching for movie title **Hangar 10**.

```
IMDbParserError                           Traceback (most recent call last)
<ipython-input-6-74c93e4688e0> in <module>
      1 from imdb import Cinemagoer
      2 ia = Cinemagoer()
----> 3 options = ia.search_movie('Hangar 10')
      4 options

~\AppData\Roaming\Python\Python36\site-packages\imdb\__init__.py in search_movie(self, title, results, _episodes)
    442             results = 20
    443         if not _episodes:
--> 444             res = self._search_movie(title, results)
    445         else:
    446             res = self._search_episode(title, results)

~\AppData\Roaming\Python\Python36\site-packages\imdb\parser\http\__init__.py in _search_movie(self, title, results)
    407     def _search_movie(self, title, results):
    408         cont = self._get_search_content('tt', title, results)
--> 409         return self.smProxy.search_movie_parser.parse(cont, results=results)['data']
    410 
    411     def _get_list_content(self, list_, page):

~\AppData\Roaming\Python\Python36\site-packages\imdb\parser\http\utils.py in parse(self, html_string, getRefs, **kwds)
    432                     self._logger.warn('%s: unable to gather refs',
    433                                       self._cname, exc_info=True)
--> 434             data = self.parse_dom(dom)
    435         else:
    436             data = {}

~\AppData\Roaming\Python\Python36\site-packages\imdb\parser\http\utils.py in parse_dom(self, dom)
    524     def parse_dom(self, dom):
    525         """Parse the given dom according to the rules specified in self.rules."""
--> 526         return Rules(self.rules).extract(dom)
    527 
    528     def postprocess_data(self, data):

~\AppData\Roaming\Python\Python36\site-packages\imdb\parser\http\piculet.py in extract(self, element, transform)
    371         :return: Extracted and optionally transformed data.
    372         """
--> 373         value = self.apply(element)
    374         if (value is None) or (value is _EMPTY) or (not transform):
    375             return value

~\AppData\Roaming\Python\Python36\site-packages\imdb\parser\http\piculet.py in apply(self, element)
    515         data = {}
    516         for rule in self.rules:
--> 517             extracted = rule.extract(subroot)
    518             data.update(extracted)
    519         return data if len(data) > 0 else _EMPTY

~\AppData\Roaming\Python\Python36\site-packages\imdb\parser\http\piculet.py in extract(self, element)
    587                     continue
    588                 data[key] = values if self.extractor.transform is None else \
--> 589                     list(map(self.extractor.transform, values))
    590                 # _logger.debug('extracted value for "%s": "%s"', key, data[key])
    591         return data

~\AppData\Roaming\Python\Python36\site-packages\imdb\parser\http\searchMovieParser.py in <lambda>(x)
     62                 transform=lambda x: (
     63                     analyze_imdbid(x.get('link')),
---> 64                     analyze_title(x.get('info', '')),
     65                     x.get('akas'),
     66                     x.get('cover url')

~\AppData\Roaming\Python\Python36\site-packages\imdb\utils.py in analyze_title(title, canonical, canonicalSeries, canonicalEpisode)
    325     if series_title:
    326         # It's an episode of a series.
--> 327         series_d = analyze_title(series_title, canonical=canonicalSeries)
    328         oad = sen = ep_year = ''
    329         # Plain text data files format.

~\AppData\Roaming\Python\Python36\site-packages\imdb\utils.py in analyze_title(title, canonical, canonicalSeries, canonicalEpisode)
    430         title = title[1:-1].strip()
    431     if not title:
--> 432         raise IMDbParserError('invalid title: "%s"' % original_t)
    433     if canonical is not None:
    434         if canonical:

IMDbParserError: invalid title: """"

```

#### Version of Cinemagoer, Python and OS

**NOTICE: please always try the latest version from the repository before submitting a bug.**

- **Python:** `python3 -V` or, if you are using Python 2, `python -V`
Python 3.6.4

- **Cinemagoer:** `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2, `python -c 'import imdb ; print(imdb.VERSION)'`
2022.02.11

- **OS:** `python -c 'import platform ; print(platform.uname())'`
system='Windows', release='10', version='10.0.19041', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 10, GenuineIntel'

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```from imdb import Cinemagoer
ia = Cinemagoer()
options = ia.search_movie('Hangar 10')
options
```

#### What's the expected result?

- Retrieve info related to movie Hangar 10 or list of possible movies.

#### What's the actual result?

- IMDbParserError: invalid title: """"

#### Additional details

-

**Comment by tsaklidis** [comment]
Actually it is not the "Hangar 10" that cause the problem.
There is a title with extra quotes in it: ` ""Hanging Around Positive people"" (2021) (Podcast Episode) `

<hr>

The complete response before the break is:

1.  Hangar 10 (2014) 
2.  Hangar 18 (1980) 
3.  Hangar 18 (2008) (Short) 
4.  Hangar 1: The UFO Files (2014) (TV Series) 
5.  Hangar 17 (1992) (TV Series) 
6.  Mystery Science Theater 3000 (1988) (TV Series)
7.  Hangar 18 (1989) (TV Episode)  - Season 1 | Episode 19  - Mystery Science Theater 3000 (1988) (TV Series)  
8.  Sci-Fi Spring Break (2011) (TV Series)
9.  Hangar 18 (2011) (TV Episode)  - Season 1 | Episode 1  - Sci-Fi Spring Break (2011) (TV Series)  
10.  Good Bad Flicks (2010) (TV Series)
11.  Hangar 18 (2021) (TV Episode)  - Season 12 | Episode 23  - Good Bad Flicks (2010) (TV Series)  
12.  Hangar 18 (2018) (Podcast Series) 
13.  Hangar 18 (1980) (2020) (Podcast Episode)  - Season 1 | Episode 74  - Vintage Video (2020) (Podcast Series)  
14.  Hangar 8 (2019) (Short) 
15.  Kidnappningar 10 (2021) (Podcast Episode) - Spöktimmen (2016) (Podcast Series)  
16.  Hangar Rats (2009) 
17.  Hangar (2004) (Short) 
18.  Yo Soy El Artista (2014) (TV Series)
19.  Hangar (2014) (TV Episode)  - Season 1 | Episode 5  - Yo Soy El Artista (2014) (TV Series)  
20.  Yo Soy El Artista (2014) (TV Series)
21.  Hangar (2014) (TV Episode)  - Season 1 | Episode 4  - Yo Soy El Artista (2014) (TV Series)  
22.  Hangar (2007) (Short) 
23.  Megadeth: Hangar 18 (1991) (Music Video) 
24.  Modern Marvels (1993) (TV Series)
25.  Hangars (2002) (TV Episode)  - Season 8 | Episode 25  - Modern Marvels (1993) (TV Series)  
26.  Hangar B (2014) (Short) 
27.  Hangar No. 5 (2008) (Short) 
28.  Dhangarwada (2015) 
29.  The Hangar (2012) (TV Series) 
30.  Thangaratham (2017) 
31.  Sangarshana (1983) 
32.  New Beginnings (2020) (TV Series)
33.  Hangarin (2021) (TV Episode)  - Season 1 | Episode 76  - New Beginnings (2020) (TV Series)  
34.  Ang probinsyano (2015) (TV Series)
35.  Hangarin (2022) (TV Episode)  - Season 9 | Episode 121  - Ang probinsyano (2015) (TV Series)  
36.  Ang probinsyano (2015) (TV Series)
37.  Hangarin1 (2016) (TV Episode)  - Season 2 | Episode 58  - Ang probinsyano (2015) (TV Series)  
38.  Battlestar Galactica: Razor Flashbacks (2007) (TV Mini Series)
39.  The Hangar (2007) (TV Episode)  - Season 1 | Episode 2  - Battlestar Galactica: Razor Flashbacks (2007) (TV Mini Series)  
40.  Encantadia (2016) (TV Series)
41.  Hangarin (2017) (TV Episode)  - Season 1 | Episode 185  - Encantadia (2016) (TV Series)  
42.  Bhangagara (1954) 
43.  Thanga Rangan (1978) 
44.  Bhangarh: The Last Episode (2017) 
45.  UFO Files (2004) (TV Series)
46.  Hangar 18: The UFO Warehouse (2006) (TV Episode)  - Season 3 | Episode 12  - UFO Files (2004) (TV Series)  
47.  Hangar18Radio attacks!! (2020) (Podcast Episode) - The Paranormal Son (2020) (Podcast Series)  
48.  Screaming Horror Theater (2005) (TV Series)
49.  An Annoyance at Hangar 18 (2007) (TV Episode)  - Season 1 | Episode 4  - Screaming Horror Theater (2005) (TV Series)  
50.  Hangar Blues (in development) (Short) 
51.  Talk im Hangar-7 (2010) (TV Series) 
52.  Ghoom Bhangar Gaan (1965) 
53.  Trip to Bhangarh: Asia's Most Haunted Place (2014) 
54.  Buying Alaska (2012) (TV Series)
55.  Hangar Homes (2013) (TV Episode)  - Season 2 | Episode 10  - Buying Alaska (2012) (TV Series)  
56.  Bibi et Geneviève (1988) (TV Series)
57.  Drôle de hangar (1991) (TV Episode)  - Season 4 | Episode 16  - Bibi et Geneviève (1988) (TV Series)  
58.  GT Academy USA (2011) (TV Series)
59.  Hazard Hangar (2013) (TV Episode)  - Season 3 | Episode 5  - GT Academy USA (2011) (TV Series)  
60.  Auf Streife - Die Spezialisten (2015) (TV Series)
61.  Hangar Games (2018) (TV Episode)  - Season 1 | Episode 569  - Auf Streife - Die Spezialisten (2015) (TV Series)  
62. Season 1 | Episode 6,553  - See the World by Train (1987) (TV Series)
63.  Hangarî no asa (2005) (TV Episode)  - Season 1 | Episode 6,553  - See the World by Train (1987) (TV Series)  
64.  Power Rangers Beast Morphers (2019) (TV Series)
65.  Hangar Heist (2019) (TV Episode)  - Season 1 | Episode 6  - Power Rangers Beast Morphers (2019) (TV Series)  
66.  Mano Ya Na Mano (2007) (TV Series)
67.  Bhangarh Fort (TV Episode)  - Season 1 | Episode 57  - Mano Ya Na Mano (2007) (TV Series)  
68.  Bhangagara (1990) 
69.  GTAV Comedy (2013) (TV Series)
70.  3 Men 1 Hangar (2014) (TV Episode)  - Season 1 | Episode 3  - GTAV Comedy (2013) (TV Series)  
71.  Hangar Dance (2007) (Short) 
72.  Hotrod Hangar (2008) (TV Mini Series) 
73.  Hanging Around (1996) (Short) 
74.  Changa Revisited (2016) 
75.  RiffTrax Presents: Hangar 18 (2017) (Video) 
76.  Engal Thanga Raja (1973) 
77.  America's Hangar (2007) (TV Movie) 
78.  Al Hadira: The Hangar (2019) (Short) 
79.  Dans le secret des hangars (2015) 
80.  Self Story (2013) (TV Series)
81.  Full Metal Hangar (2014) (TV Episode)  - Season 1 | Episode 5  - Self Story (2013) (TV Series)  
82.  Tickle on the Tum (1984) (TV Series)
83.  Just Hanging Around (1988) (TV Episode)  - Season 4 | Episode 12  - Tickle on the Tum (1984) (TV Series)  
84.  Garuda Garvabhangam (1936) 
85. California's Gold (1991) (TV Series)
86.  Huts and Hangars (1995) (TV Episode) - California's Gold (1991) (TV Series)  
87.  Megh Bhanga Rodh (1964) 
88.  Avan Oru Ahangari (1980) 
89.  Mad Mad House (2004) (TV Series)
90.  Hanging Around (2004) (TV Episode)  - Season 1 | Episode 5  - Mad Mad House (2004) (TV Series)  
91.  Garuda Garvabhangam (1943) 
92. Freetime (1980) (TV Series)
93.  Hanging Around (1985) (TV Episode) - Freetime (1980) (TV Series)  
94.  Premiere (1977) (TV Series)
95.  Hanging Around (1978) (TV Episode)  - Season 2 | Episode 3  - Premiere (1977) (TV Series)  
96.  Wingman's Hangar (2012) (TV Series) 
97.  Mahatma Udhangar (1947) 
98.  Endurance (2002) (TV Series)
99.  Hanging Around (2006) (TV Episode)  - Season 5 | Episode 2  - Endurance (2002) (TV Series)  
100.  Megh Bhanga Roddur (2013) (Short) 
101.  D.P.D. Echo 1 (TV Series)
102.  Hanging Around (TV Episode)  - Season 1 | Episode 3  - D.P.D. Echo 1 (TV Series)  
103.  Building Wild (2014) (TV Series)
104.  Hilltop Hangar (2015) (TV Episode)  - Season 2 | Episode 5  - Building Wild (2014) (TV Series)  
105.  Tosh.0 (2009) (TV Series)
106.  Naked Hanging Artist (2018) (TV Episode)  - Season 10 | Episode 14  - Tosh.0 (2009) (TV Series)  
107.  Hungary? No! I'm HANGARY! (2021) (Podcast Episode) - Brad and Britt Cast (2020) (Podcast Series)  
108.  Garuda Garvabhangam (1929) 
109.  Boys Over Flowers (1996) (TV Series)
110.  Can I Hang Around You? (1996) (TV Episode)  - Season 1 | Episode 18  - Boys Over Flowers (1996) (TV Series)  
111.  The Bhangarh Fort (2018) (Podcast Episode) - Haunted Places (2017) (Podcast Series)  
112.  Aircraft Doctors (2019) (TV Series)
113.  Neuer Hangar, neues Glück (2020) (TV Episode)  - Season 2 | Episode 1  - Aircraft Doctors (2019) (TV Series)  
114.  Disney Family Sundays (2019) (TV Series)
115.  Star Wars: Hanging Art (2020) (TV Episode)  - Season 1 | Episode 27  - Disney Family Sundays (2019) (TV Series)  
116.  Khela Bhangar Khela (2019) (Video) 
117.  Khela Bhangar Khela (1957) 
118.  Die besten Köche der Welt - Zu Gast im Ikarus (2015) (TV Series)
119.  Best Of Hangar-7 (2020) (TV Episode)  - Season 6 | Episode 14  - Die besten Köche der Welt - Zu Gast im Ikarus (2015) (TV Series)  
120.  Better Than Garbage (2016) (Short) 
121.  Dmax Doku (2007) (TV Series)
122.  Der Hot-Rod-Hangar (2009) (TV Episode)  - Season 2 | Episode 14  - Dmax Doku (2007) (TV Series)  
123.  Dhimaner Dinkaal (2017) (TV Series)
124.  Khela Bhangar Khela (2017) (TV Episode)  - Season 1 | Episode 9  - Dhimaner Dinkaal (2017) (TV Series)  
125.  Aircraft Doctors (2019) (TV Series)
126.  Ein Gast im Hangar (2020) (TV Episode)  - Season 2 | Episode 4  - Aircraft Doctors (2019) (TV Series)  
127.  Compelled Cooperation (2015) (TV Series)
128.  Doom - E1M1: Hangar (2016) (TV Episode)  - Season 6 | Episode 1  - Compelled Cooperation (2015) (TV Series)  
129.  Project Dreams: How to Build Mazinger Z's Hangar (2020) 
130.  Flophouse (2016) (TV Series)
131.  Can Crushing at the Hangar (2016) (TV Episode)  - Season 1 | Episode 5  - Flophouse (2016) (TV Series)  
132.  One by One (1984) (TV Series)
133.  The Elephant and the Kangaroo (1987) (TV Episode)  - Season 3 | Episode 7  - One by One (1984) (TV Series)  
134.  Art from Changing Arctic (2009) 
135. You Live in What? (2012) (TV Series)
136.  Cooler, Clock Tower, Hangar (2013) (TV Episode) - You Live in What? (2012) (TV Series)  
137.  Kommissar Brahm (1967) (TV Series)
138.  Zwischenfall im Hangar (1967) (TV Episode)  - Season 1 | Episode 6  - Kommissar Brahm (1967) (TV Series)  
139.  Adulting with Emma Chamberlain (2019) (TV Series)
140.  How To Hang Art Like A Pro! (2019) (TV Episode)  - Season 1 | Episode 9  - Adulting with Emma Chamberlain (2019) (TV Series)  
141.  Another Period (2013) (TV Series)
142.  Little Orphan Garfield (2018) (TV Episode)  - Season 3 | Episode 9  - Another Period (2013) (TV Series)  
143.  Kasintahan sa pangarap (1951) 
144. Tribunal (1989) (TV Series)
145.  Le hangar de la discorde (1990) (TV Episode) - Tribunal (1989) (TV Series)  
146.  Rød zone (2006) (TV Series)
147.  Hangarskibet de Gaulle (2007) (TV Episode)  - Season 3 | Episode 4  - Rød zone (2006) (TV Series)  
148.  Wagle Ki Duniya (2021) (TV Series)
149.  Rajesh And Gang Arrested (2021) (TV Episode)  - Season 1 | Episode 135  - Wagle Ki Duniya (2021) (TV Series)  
150.  C'est cool! (1996) (TV Series)
151.  Jeux de l'amour et du hangar (1996) (TV Episode)  - Season 1 | Episode 22  - C'est cool! (1996) (TV Series)  
152.  Yngwie J. Malmsteen's Rising Force: Hangar 18, Area 51 (1999) (Music Video) 
153.  Tokyo Nagarathile Viseshangal (1999) 
154.  Irosin, pagputok ng araw... babaha ng dugo! (1989) 
155.  The Cardigans: Hanging Around (1999) (Music Video) 
156.  Calling All Devs (2018) (TV Series)
157.  Hangars, Interdiction and Repair (2018) (TV Episode)  - Season 1 | Episode 9  - Calling All Devs (2018) (TV Series)  
158.  Trumps anhangare kraver lojalitet (2021) (Podcast Episode) - USApodden (2016) (Podcast Series)  
159.  The Stranglers: Hanging Around (1977) (Music Video) 
160.  The Late Show with Stephen Colbert (2015) (TV Series)
161.  50 Cent/Rachel Brosnahan/Gary Vider (2018) (TV Episode)  - Season 3 | Episode 63  - The Late Show with Stephen Colbert (2015) (TV Series)  
162.  The Tonight Show Starring Jimmy Fallon (2014) (TV Series)
163.  Michael Strahan/Michael Angarano/Takeoff (2018) (TV Episode)  - Season 6 | Episode 49  - The Tonight Show Starring Jimmy Fallon (2014) (TV Series)  
164.  232: NFTs changing artistsaEU lives (2021) (Podcast Episode) - The Cha Wilde Show (2019) (Podcast Series)  
165.  'Nu gar taget - klara nagot lag hanga pa?' (2020) (Podcast Episode) - Studio Allsvenskan (2017) (Podcast Series)  
166.  Viden om (1999) (TV Series)
167.  Exoplaneter og hangarskib i krig (2010) (TV Episode)  - Season 23 | Episode 1  - Viden om (1999) (TV Series)  
168.  Wild About New Zealand (2000) (TV Series)
169.  Whanganui & Tongariro National Parks (2013) (TV Episode)  - Season 1 | Episode 4  - Wild About New Zealand (2000) (TV Series)  
170.  Whangarei Christmas in the Park (2009) (TV Special) 
171. The Jim Bakker Show (2003) (TV Series)
172.  The World Is Changing. Are You Ready? (2022) (TV Episode) - The Jim Bakker Show (2003) (TV Series)  
173.  "Hanging Around Positive People" (2021) (Podcast Episode) - focus on Recovery.. Daily boost Podcast (2021) (Podcast Series)  
174.  The Changing Art of Skylar Ru Silva (2020) (Short) 
175.  Bhanga Gara (To Break To Create) (2006) (Short) 
176.  You Live in What? (2012) (TV Series)
177.  Bank, Airplane Hangar, Chapel (2014) (TV Episode)  - Season 3 | Episode 6  - You Live in What? (2012) (TV Series)  
178.  Snowsnaps (2018) (TV Series)
179.  Snapshot Hill / Hanging Around (2018) (TV Episode)  - Season 1 | Episode 18  - Snowsnaps (2018) (TV Series)  
180.  RV with Me (2012) (TV Series)
181.  Pechanga RV Resort Excitement! (2016) (TV Episode)  - Season 5 | Episode 2  - RV with Me (2012) (TV Series)  
182.  Gardening and Climate Change (2020) (Podcast Episode) - 5 Live Science Podcast (2018) (Podcast Series)  
183.  120 - Nathan Angelo - Recording Artist (2017) (Podcast Episode) - BowHunter Planet: A Bowhunting Podcast and much more (2017) (Podcast Series)  
184.  Onyx Kids (2016) (TV Series)
185.  Kangaroo vs Shiloh and Shasha (2017) (TV Episode)  - Season 1 | Episode 54  - Onyx Kids (2016) (TV Series)  
186.  An Elizabethan Garden Party (2021) (Podcast Episode) - Get Sleepy: Sleep meditation and stories (2019) (Podcast Series)  
187.  The Steve Wilkos Show (2007) (TV Series)
188.  Your Story Keeps Changing: Are You Lying? (2016) (TV Episode)  - Season 9 | Episode 79  - The Steve Wilkos Show (2007) (TV Series)
