### ISSUE TITLE
Statuses gone?

### ISSUE THREAD

**Issue by JDezube** [cinemagoer/cinemagoer#398]
#### Issue description

Was pulling status (e.g. "Post-Production" ) removed?

#### Version of Cinemagoer, Python and OS
python 3.10.2
cinemagoer 2022.02.11
uname_result(system='Windows', node='DESKTOP-BUS9NKA', release='10', version='10.0.19043', machine='AMD64')

#### Steps to reproduce the issue

from imdb import Cinemagoer
ia=Cinemagoer()
movie=ia.get_movie(15398776)
'status' in movie.infoset2keys['main']

#### What's the expected result?
True, or at least it used to be. 

#### What's the actual result?
False

#### Additional details
I loaded all info sets and looked.  As far as I can tell if I now wanted to know if a movie is done, I would have to pull in the 'akas' data set and check 'release dates'-- is that true?

I did check the Changelog, but saw nothing about status mentioned.  It's still on the webpage, e.g. https://www.imdb.com/title/tt15398776/ says "Post-Production" right above Expected July 21, 2023

**Comment by alberanid** [comment]
thanks for the report: yes, it was bugged. It's fixed now.

The correct keywords are:
* "production status"
* "production status updated"
* "production comments"
* "production note"

Also, please consider that we parse the `/reference` page; e.g.: https://www.imdb.com/title/tt15398776/reference
