### ISSUE TITLE
Please fix this error 

### ISSUE THREAD

**Issue by Sahidmalik07** [cinemagoer/cinemagoer#417]
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find?q=sooryavanshi+-&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 403: 'Forbidden'>}

**Comment by alberanid** [comment]
closing as duplicate of #415
