### ISSUE TITLE
failure to parse Persons pages

### ISSUE THREAD

**Issue by alberanid** [cinemagoer/cinemagoer#421]
#### Issue description

The Person parsers are broken.

#### Steps to reproduce the issue

```python
#!/usr/bin/env python

import imdb
ia = imdb.Cinemagoer()
jr = ia.get_person('0000210', info='main')
print('%s: %s' % (jr.getID(), jr.get('name')))
for key in sorted(jr.keys()):
    print('%s: %s' % (key, jr.get(key)))
```

**Comment by alberanid** [comment]
some preliminary work already done and committed, but the HTML is quite different and many fixes will be required (currently no information in parsed correctly).

**Comment by xalienxx** [comment]
> some preliminary work already done and committed, but the HTML is quite different and many fixes will be required (currently no information in parsed correctly).

Better than before, 80% of the results are now showing for the search keywords. (Except: Interstellar, Wednesday, Foundation...)
Installed from packages does not work. I use directly git clone from this repository.

**Comment by alberanid** [comment]
> > some preliminary work already done and committed, but the HTML is quite different and many fixes will be required (currently no information in parsed correctly).
> 
> Better than before, 80% of the results are now showing for the search keywords. (Except: Interstellar, Wednesday, Foundation...) Installed from packages does not work. I use directly git clone from this repository.

this issue is for the pages about persons; for search results use #419. From my tests, Interstellar, Wednesday, Foundation should work now.

**Comment by alberanid** [comment]
The Person parsers should be mostly working, now.

There is however a huge limitation: for each role ("actor", "actress", "director", "composer", "producer", ...) of a person only few results - the ones that are currently in production and about 15 old ones - are present in the HTML so the returned list is very limited.

Maybe there is another page with all the titles a person worked in?

**Comment by xalienxx** [comment]
> The Person parsers should be mostly working, now.
> 
> There is however a huge limitation: for each role ("actor", "actress", "director", "composer", "producer", ...) of a person only few results - the ones that are currently in production and about 15 old ones - are present in the HTML so the returned list is very limited.
> 
> Maybe there is another page with all the titles a person worked in?

Yes.Interstellar, Wednesday, Foundation results are shown successfully now. What I wanted info was - [poster/title/release info/ratings/plot/genres].

Here's how I solved it from my side: 

Casting information solved currently with N/A exception. However, Once I get imdb data, I store it on a database.If do a return search within 2 days, the data in the database will be used.

**Comment by johnhudock** [comment]
Pointed out by ayar in another thread, this link seems to have the full list:

https://www.imdb.com/name/nm0005251/fullcredits/

**Comment by alberanid** [comment]
@johnhudock that's correct: I'm closing this issue and continue the discussion in #424
