### ISSUE TITLE
308 redirect error when searching for films

### ISSUE THREAD

**Issue by dbatten5** [cinemagoer/cinemagoer#432]
#### Issue description

When searching for a film using `search_movie`, a 308 is returned. Seems like this is due to the fact that 
`'https://www.imdb.com/find?q=movie+name&s=tt'` is used for the search url, but this has been permanantly
redirected to `'https://www.imdb.com/find/?q=movie+name&s=tt'`.

#### Version of Cinemagoer, Python and OS

- **Python:** 3.9.15
- **Cinemagoer:** 2022.12.04
- **OS:** uname_result(system='Darwin', node='Don.local', release='20.6.0', version='Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64', machine='x86_64')

**Comment by mhdzumair** [comment]
It seems this issue was fixed in https://github.com/cinemagoer/cinemagoer/commit/c1b7abcc32344a9a28aef83301659b483b70e49f

**Comment by alberanid** [comment]
yes, it was already fixed.  Yesterday I've also release version 2022.12.27 on pypi.
