### ISSUE TITLE
Filmography is still missing in person info in latest release & unable to get latest version

### ISSUE THREAD

**Issue by nikhiltalreja** [cinemagoer/cinemagoer#433]
#### Issue description

I have followed the bug fixes, filmography/role has been fixed, yet I am not getting Filmography in person info

#### Version of Cinemagoer, Python and OS

**NOTICE: please always try the latest version from the repository before submitting a bug.**

- **Python:** Python 3.9.2
- **Cinemagoer:** 2022.02.11
- **OS:** ('Darwin', 'apples-MacBook-Air.local', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64', 'x86_64', 'i386')

```**Cinemagoer installation log**
Collecting git+https://github.com/cinemagoer/cinemagoer
  Cloning https://github.com/cinemagoer/cinemagoer to /private/var/folders/wy/mh5qml45607gbv0q72rcv_gm0000gn/T/pip-req-build-kq2f84xq
  Running command git clone --filter=blob:none --quiet https://github.com/cinemagoer/cinemagoer /private/var/folders/wy/mh5qml45607gbv0q72rcv_gm0000gn/T/pip-req-build-kq2f84xq
  Resolved https://github.com/cinemagoer/cinemagoer to commit f23449c1ac5ee9ab728874c3fa18ba05a285ed9b
  Preparing metadata (setup.py) ... done
Requirement already satisfied: SQLAlchemy in /usr/local/lib/python3.9/site-packages (from cinemagoer==2022.12.27) (1.4.44)
Requirement already satisfied: lxml in /usr/local/lib/python3.9/site-packages (from cinemagoer==2022.12.27) (4.9.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.9/site-packages (from SQLAlchemy->cinemagoer==2022.12.27) (2.0.1)
```

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```python
#!/usr/bin/env python

import imdb
ia = imdb.Cinemagoer()
person = ia.get_person('0000206')
person['filmography'].keys()

```

#### What's the expected result?

- I should get all the films done by the actor

#### What's the actual result?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/imdb/utils.py", line 1506, in __getitem__
    rawData = self.data[key]
KeyError: 'filmography'
```

#### Additional details

- I have uninstalled and reinstalled using github link and pip3 multiple times

**Comment by alberanid** [comment]
Version `2022.02.11` is quite old; latest is `2022.12.27`.

Your code works with the latest version, returning `['actor', 'producer', 'additional crew']`, but keep in mind that currently the parser for person's filmography is quite limited. See #424 

You have to find out how to properly update your local installation.

(closing the issue, but feel free to add details if needed to solve your specific problem)

**Comment by nikhiltalreja** [comment]
Yes I need to know what am I doing wrong when uninstalling reinstalling the
repository.

I have also tried removing the entire package folder also.

I am following all steps. I know that the bug was resolved. But I am not
getting the latest repository.

**Comment by alberanid** [comment]
In general, it's a good idea to work using virtual environments, so that the host system is not polluted with third-party modules.

For a guide, see https://realpython.com/python-virtual-environments-a-primer/

**Comment by nikhiltalreja** [comment]
After uninstalling cinemagoer and running this command 'python3 -c 'import imdb ; print(imdb.VERSION)'' I was still getting the older version. After doing some digging I found **imdb and IMDbPY-2021.4.18.dist-info** hence I had to manually delete it. The older version went away...

**python3 -c 'import imdb ; print(imdb.VERSION)'**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'imdb'
```

Now I have installed cinemagoer from github link however I still get

**python3 -c 'import imdb ; print(imdb.VERSION)'**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'imdb'
```

Why is this happening? Does cinemagoer depend on imdb folder?

**Comment by nikhiltalreja** [comment]
> After uninstalling cinemagoer and running this command 'python3 -c 'import imdb ; print(imdb.VERSION)'' I was still getting the older version. After doing some digging I found **imdb and IMDbPY-2021.4.18.dist-info** hence I had to manually delete it. The older version went away...
> 
> **python3 -c 'import imdb ; print(imdb.VERSION)'**
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'imdb'
> ```
> 
> Now I have installed cinemagoer from github link however I still get
> 
> **python3 -c 'import imdb ; print(imdb.VERSION)'**
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'imdb'
> ```
> 
> Why is this happening? Does cinemagoer depend on imdb folder?

I think I found the issue and resolution here - 
https://stackoverflow.com/questions/52329776/two-different-site-packages-on-macos
