### ISSUE TITLE
Critics review not working

### ISSUE THREAD

**Issue by vrayv** [cinemagoer/cinemagoer#439]
It seems critics review parsing is not working anymore. By looking at the data it seems html page is changed (/criticsreview).

Example:

critics_review = self.imdb.get_movie_critic_reviews(imdb_id)
metascore = critics_review.get('data').get('metascore')

This will always return null even for movies with clear metascore result.

**Comment by tableaukun** [comment]
Can also confirm this

**Comment by theotherp** [comment]
Can I help get this fixed?

**Comment by alberanid** [comment]
I can confirm that the `DOMHTMLCriticReviewsParser` class in imdb.parser.http.movieParser needs to be fixed to parse the new data format.

**Comment by theotherp** [comment]
Thanks for the hint, @alberanid. That allowed me to fix it.
