### ISSUE TITLE
Cant get rating!

### ISSUE THREAD

**Issue by bluboyo** [cinemagoer/cinemagoer#440]
I get this error when i try to get a movie rating. Havent changed my scirpt. It just stopped working.
OS Ubuntu 22.04
Pythonversion 3.10.6

Traceback (most recent call last):
File "/home/user/.local/lib/python3.10/site-packages/imdb/utils.py", line 1503, in getitem
rawData = self.data[key]
KeyError: 'Arithmetic mean'

**Comment by grndng** [comment]
Can you please elaborate on how you try to access the rating since from what you post it's rather difficult to reconstruct the error. However, the following example should work:

```python
from imdb import Cinemagoer
ia = Cinemagoer()
example_movie = ia.get_movie("0133093") # id 0133093 is for "The Matrix"
example_movie_rating = example_movie.get("rating") # using the get method with rating as keyword
```

**Comment by bluboyo** [comment]
Hi! Heres some code. This worked fine a few months ago. Plot at rating gives me an error

Name: cinemagoer
Version: 2022.12.27

from imdb import Cinemagoer
ia = Cinemagoer()
movie = ia.get_movie(imdb)
ia.update(movie, info=['taglines', 'vote details'])
rating = movie['Arithmetic mean']plot = movie['plot'][0]

**Comment by alberanid** [comment]
hi @bluboyo : it's "arithmetic mean" (lowercase) and not "Arithmetic mean".  Tested with the latest version, and it works.

Closing this issue; feel free to open it again in case of problems.
