### ISSUE TITLE
Can't get plot

### ISSUE THREAD

**Issue by scegielski** [cinemagoer/cinemagoer#441]
#### Issue description

The 'plot' key no longer seems available for some movies

#### Version of Cinemagoer, Python and OS
cinemagoer-2023.2.5
Python 3.8.5
Windows 7

#### Steps to reproduce the issue

```python
#!/usr/bin/env python
from imdb import Cinemagoer
ia = Cinemagoer()
m=ia.get_movie('0082970')
ia.update(m)
plot = m['plot']
```

#### What's the expected result?
A string containing the plot of the movie
- 

#### What's the actual result?
Traceback (most recent call last):
KeyError: 'plot'
- 

#### Additional details

-

**Comment by alberanid** [comment]
That same code works for me using Cinemagoer 2023.03.19; can you upgrade and try it again?

Thanks for the report.

**Comment by scegielski** [comment]
Yes, it is now working with  Cinemagoer 2023.03.19.   Thanks for the fix!
