### ISSUE TITLE
Minor issue: movie rating type sometimes is string (instead of float)

### ISSUE THREAD

**Issue by Rabelaiss** [cinemagoer/cinemagoer#448]
#### Issue description

When using the `languages` argument, in some cases `type(movie['rating'])` is `str` rather than `float`.

#### Version of Cinemagoer, Python and OS

- **Python:** 3.10.1
- **Cinemagoer:** 2023.03.19
- **OS:** Windows 11 v10.0.22621

#### Steps to reproduce the issue

```python
ia = Cinemagoer()
ia.get_movie('14592064')['rating'], ia.get_movie('0225947')['rating']
(6.0, 3.7)
```

```python
ia = Cinemagoer(languages='it-IT')
ia.get_movie('14592064')['rating'], ia.get_movie('0225947')['rating']
(6.0, '3,7')
```

I guess this is due to the use of comma for decimal notation in Italy.

This is a minor issue which can be easily solved with `float(str(movie['rating']).replace(',','.'))`

**Comment by alberanid** [comment]
thanks for the report, I've introduced a blind fix since I'm unable to reproduce it.
