### ISSUE TITLE
Cinemagoer returning Incomplete Filmography

### ISSUE THREAD

**Issue by acronomic** [cinemagoer/cinemagoer#449]
#### Cinemagoer returning incomplete filmography

*Hi, I'm trying to get the full filmography for an editor, but I'm noticing only a partial credit list is being returned.  In the following example, I'm searching for all films edited by Walter Murch.*

#### Version of Cinemagoer, Python and OS

Cinemagoer: 2022.12.27
Python: 3.8.16
OS: macOS Monterey v12.6

#### Steps to reproduce the issue

```python
#!/usr/bin/env python

import imdb
ia = imdb.Cinemagoer()
editor = ia.search_person('Walter Murch')[0]
p = ia.get_person(editor.personID)
f=p['filmography']["editor"]
print(len(f))
```

#### Expected result is 27, but the program is returning 15.

Walter Murch Imdb Page](https://www.imdb.com/name/nm0004555/?ref_=fn_al_nm_1)

#### Additional details

Tossing darts in the dark, I have tried various combinations of updates such as  `ia.update(p)`, `ia.update(p['filmography'])`, `ia.update(p['filmography']['editor'])`, etc.  but none of these seem to work.

**Comment by alberanid** [comment]
Please upgrade to the repository version with `pip install git+https://github.com/cinemagoer/cinemagoer`; the issue is fixed.

Reopen the issue if you still have problems.
