### ISSUE TITLE
AKA's doesn't work properly, cg only fetches a couple of titles, `akasLanguages` missing languages from the tuples.

### ISSUE THREAD

**Issue by pcroland** [cinemagoer/cinemagoer#451]
![img](https://i.kek.sh/4xFQ7mec7Rc.png)

I tried to fetch the titles for Amélie (tt0211915). It has like ~60 titles, but cg wasn't able to fetch them all.

**Comment by ale86ch** [comment]
Hi, I am having the same issue, any update?

**Comment by jimlynnjulian** [comment]
From a recent response to ale86's post elsewhere:

"Hi @ale86ch , unfortunately I think we will never support the complete list of AKAs and, in general, of any resource that is only partially shown in the new design of the IMDb's web pages.

We just parse the HTML; to access the complete list, you would need to issue one or more async queries, and it would be quite difficult to emulate that for us."

**Comment by alberanid** [comment]
I can confirm that we can't do anything to solve this, unless IMDb starts serving again all the data in the HTML.

Sorry, I'm closing this issue until any news.
