### ISSUE TITLE
DTD errors in xml, single quote errors in json

### ISSUE THREAD

**Issue by jimlynnjulian** [cinemagoer/cinemagoer#461]
1. The xml returned in "print(movie.asXML('title'))
" refers to a url , "https://cinemagoer.github.io/static/dtd/cinemagoer.dtd", for the xml dtd.
 A '404' results from attempts to accessthe url.
I ended upplacing a copy of the dtd from the source code, in the same folder as the xml.

2. The json returned uses single quotes where double quotes are standard. This can cause an error in some applications.

**Comment by uyar** [comment]
Thanks for pointing out the DTD URL error, I've fixed it.

**Comment by jimlynnjulian** [comment]
Is there a way to test that? When I visit the link in the xml output, the browser opens but goes to an already open link in the browser.

**Comment by jimlynnjulian** [comment]
When I try tofollow the xml dtd link, nothing happens.
