### ISSUE TITLE
Date Retrieval Not Working

### ISSUE THREAD

**Issue by reidralston0** [cinemagoer/cinemagoer#469]
#### Issue description

Date retrieval for person not working. Returns "None" when there should be a date.

#### Version of Cinemagoer, Python and OS

- **Python:** 3.7.4
- **Cinemagoer:** 2023.05.01
- **OS:** Windows 10.0.19041

#### Steps to reproduce the issue

```python
#!/usr/bin/env python

person = ia.get_person('0000017')
d_date = person.get('death date')
print(d_date)
```

#### What's the expected result?
May 6, 1992
- 

#### What's the actual result?
None
- 

#### Additional details

-

**Comment by Cj1m** [comment]
I am facing the same issue, in addition I am unable to access 'birth date' and 'death cause' too.

It seems this data is missing by default now:
```
person.keys();
//['headshot', 'imdbID', 'name', 'filmography', 'mini biography', 'canonical name', 'long imdb name', 'long imdb canonical name', 'full-size headshot']
```
It might be that we need to add to the `info` tuple parameter in `get_person`. By default this is set to `('main', 'filmography', 'biography')`

**Comment by jugoprex** [comment]
Any tips on how to work around this? I have the same issue with 'birth date'.

**Comment by jfadams1963** [comment]
Has anyone made progress on this?

I'm working on solving these and similar issues with empty/missing datasets, and will gladly share what I find.

A recent example of what I'm seeing is trying to get quotes using 'The Matrix' as a test. The official website displays a long list of quotes, yet my attempt turns up an empty dataset:

In [7]: m
Out[7]: <Movie id:0133093[http] title:_The Matrix (1999)_>

In [8]: m.infoset2keys
Out[8]: {}

In [9]: db.update(m, info=['quotes', 'faqs', 'goofs', 'trivia'])

In [11]: m.current_info
Out[11]: ['quotes', 'faqs', 'goofs', 'trivia']

In [12]: m.get('quotes')
(crickets)

In [13]: m.infoset2keys
Out[13]: {'quotes': [], 'faqs': [], 'goofs': [], 'trivia': ['trivia']}

Look familiar? Any ideas?

**Comment by jfadams1963** [comment]
Opening new issue related to above comment.
