### ISSUE TITLE
Incorrect 'kind' of TV Specials

### ISSUE THREAD

**Issue by entrider** [cinemagoer/cinemagoer#486]
#### Issue description

TV Special titles are misidentified as movies. 
See also #357, I believe something has changed and it needs to be fixed (again).

#### Version of Cinemagoer, Python and OS

- **Python:** Python 3.11.5
- **Cinemagoer:** 2023.10.22
- **OS:** Linux 6.5.8 x86_64

#### Steps to reproduce the issue
```
from imdb import Cinemagoer
ia = Cinemagoer()
movie = ia.get_movie('15475200') # https://www.imdb.com/title/tt15475200
print(movie['kind'])
```

**Comment by entrider** [comment]
It works for some titles though, e.g. https://www.imdb.com/title/tt16301388 is identified as 'tv special'.

**Comment by dothebart** [comment]
No, these errors showed up during postgres importing.

**Comment by dothebart** [comment]
I tried to have only CSV files dumped, but failed with that as well. should that be possible?

**Comment by uyar** [comment]
Could you start a topic under discussions about this, describing your steps? Maybe some users can help, I don't have much experience with it.
