### ISSUE TITLE
Alternative titles no longer work

### ISSUE THREAD

**Issue by Susexe** [cinemagoer/cinemagoer#507]
#### Issue description

IMDb changed the layout of their /releaseinfo page a while ago, so currently Cinemagoer extracts information only from the /reference path, which is very scarce. This probably affects release dates, too. I would greatly appreciate a fix. Thank you in advance.

#### Version of Cinemagoer, Python and OS

Cinemagoer 2023.10.22, Python 3.12.2, Windows 10.0.19045

**Comment by drakeguan** [comment]
I guess the conclusion has been made in #458 ;)

**Comment by Susexe** [comment]
The other one is a duplicate, but yes, I'm closing this. 😊
