### ISSUE TITLE
Could SQLAlchemy be an optional dependency again?

### ISSUE THREAD

**Issue by uyar** [cinemagoer/cinemagoer#75]
I never use the SQL system and I wouldn't want to have to install SQLAlchemy to run IMDbPY. Installing it by default is OK but it would be nice to again have the option not to install it.

**Comment by alberanid** [comment]
makes sense, yes!  I'll work on it later.

**Comment by uyar** [comment]
This works when installing with

> python setup.py --without-sqlalchemy install

but I couldn't make it work with pip installs. I tried

> pip install imdbpy --install-option="--without-sqlalchemy"

but this downloaded SQLAlchemy anyway (because it's listed in install_requires?) and then complained about not recognizing the option.

A simpler way to handle this could be using extras_require as in:

> 'extras_require': {'sqlalchemy': [SQLAlchemy]}

and then installing with

> pip install imdbpy[sqlalchemy]

but then SQLAlchemy wouldn't be installed by default.

**Comment by uyar** [comment]
So, something like this setup below works:

```python
    'install_requires': ['lxml'],
    'extras_require': {
        'sqlalchemy': ['SQLAlchemy', 'sqlalchemy-migrate'],
        'dev': ['flake8', 'flake8-isort'],
        'test': ['pytest', 'pytest-cov'],
    },
```

**Comment by alberanid** [comment]
Cool, I'll try this solution asap!

**Comment by alberanid** [comment]
Cool, I'll try this solution asap!

**Comment by alberanid** [comment]
Doesn't seem to work for me.
Code in https://github.com/alberanid/imdbpy/tree/issue-75-sqlalchemy-optional-for-pip (I left the 'features' option, too)

Commands:

    virtualenv -p python3 issue75
    ./issue75/bin/pip3 install git+file:///path/to/imdbpy/local/git/repo --install-option="--without-sqlalchemy"

Output:

> /tmp/d/lib/python3.5/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
>   cmdoptions.check_install_build_global(options)
> Collecting git+file:///home/da/git/imdbpy/imdbpy
>   Cloning file:///home/da/git/imdbpy/imdbpy to /tmp/pip-b7e15gpl-build
> Collecting sqlalchemy-migrate (from IMDbPY==6.3.dev20171126)
>   Using cached sqlalchemy-migrate-0.11.0.tar.gz
> Collecting SQLAlchemy (from IMDbPY==6.3.dev20171126)
>   Using cached SQLAlchemy-1.1.15.tar.gz
> Collecting lxml (from IMDbPY==6.3.dev20171126)
>   Downloading lxml-4.1.1.tar.gz (2.4MB)
>     100% |████████████████████████████████| 2.4MB 355kB/s
> Collecting pbr>=1.8 (from sqlalchemy-migrate->IMDbPY==6.3.dev20171126)
>   Downloading pbr-3.1.1.tar.gz (102kB)
>     100% |████████████████████████████████| 112kB 1.1MB/s
> Collecting decorator (from sqlalchemy-migrate->IMDbPY==6.3.dev20171126)
>   Downloading decorator-4.1.2.tar.gz
> Collecting six>=1.7.0 (from sqlalchemy-migrate->IMDbPY==6.3.dev20171126)
>   Downloading six-1.11.0.tar.gz
> Collecting sqlparse (from sqlalchemy-migrate->IMDbPY==6.3.dev20171126)
>   Downloading sqlparse-0.2.4.tar.gz (61kB)
>     100% |████████████████████████████████| 71kB 1.9MB/s
> Collecting Tempita>=0.4 (from sqlalchemy-migrate->IMDbPY==6.3.dev20171126)
>   Using cached Tempita-0.5.2.tar.gz
> Skipping bdist_wheel for sqlalchemy-migrate, due to binaries being disabled for it.
> Skipping bdist_wheel for SQLAlchemy, due to binaries being disabled for it.
> Skipping bdist_wheel for lxml, due to binaries being disabled for it.
> Skipping bdist_wheel for pbr, due to binaries being disabled for it.
> Skipping bdist_wheel for decorator, due to binaries being disabled for it.
> Skipping bdist_wheel for six, due to binaries being disabled for it.
> Skipping bdist_wheel for sqlparse, due to binaries being disabled for it.
> Skipping bdist_wheel for Tempita, due to binaries being disabled for it.
> Installing collected packages: pbr, SQLAlchemy, decorator, six, sqlparse, Tempita, sqlalchemy-migrate, lxml, IMDbPY
>   Running setup.py install for pbr ... error
>     Complete output from command /tmp/d/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-olpqe3b6/pbr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-92aqzb_i-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/d/include/site/python3.5/pbr --without-sqlalchemy:
>     usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>        or: -c --help [cmd1 cmd2 ...]
>        or: -c --help-commands
>        or: -c cmd --help
>
>     error: option --without-sqlalchemy not recognized
>
>     ----------------------------------------
> Command "/tmp/d/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-olpqe3b6/pbr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-92aqzb_i-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/d/include/site/python3.5/pbr --without-sqlalchemy" failed with error code 1 in /tmp/pip-build-olpqe3b6/pbr/

**Comment by uyar** [comment]
My comment was ambiguous. The install option command doesn't work, "pip install imdbpy[sqlalchemy]" does. I tried without the features setting.

**Comment by alberanid** [comment]
I see.  The ideal solution is to have the dependency on by default.  Not sure if it's possible using pip, then.

**Comment by uyar** [comment]
Yes. I couldn't find a way to achieve that.

**Comment by alberanid** [comment]
Internet brain, work for us: https://stackoverflow.com/questions/47494885/how-to-turn-off-a-feature-dependency-installing-a-package-with-pip

(I really doubt it, but... ;))
