### ISSUE TITLE
Character pages are going to change on Dec 6th, 2017

### ISSUE THREAD

**Issue by uyar** [cinemagoer/cinemagoer#92]
#### Issue description

Here's the announcement:

https://getsatisfaction.com/imdb/topics/changes-to-imdb-characters

New parsers will be needed.

#### Version of IMDbPY, Python and OS

- **Python:** `python3 -V` or, if you are using Python 2, `python -V`
- **IMDbPY:** `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2, `python -c 'import imdb ; print(imdb.VERSION)'`
- **OS:** `python -c 'import platform ; print(platform.uname())'`

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python

# your code here
```

#### What's the expected result?

- 

#### What's the actual result?

- 

#### Additional details

-

**Comment by alberanid** [comment]
I think, in the long term, I'll just get rid of the Character class.  After all, while there are information (pictures and quotes) related to the new (movie,character) tuple they have introduced, I feel the support for it is more the trouble than it's worth.

**Comment by alberanid** [comment]
as a very first step, I've just removed the references to Characters in the 'http' parsers.

For the moment the rest is left untouched, since the old 'sql' parsers are still around and they are still able to manage characters from the old dataset.
